INSERT INTO statuses(Val) VALUES('Going');
INSERT INTO statuses(Val)	VALUES('Tentative');
INSERT INTO statuses(Val)	VALUES('Not going');
INSERT INTO statuses(Val)	VALUES('Presenting');
INSERT INTO users(Name,Birthdate,Introduction,Avatar,Email) VALUES('Ronai Mate', '1994.08.20','Ez en vagyok.','nincs','ronaimate@gmail.com');
INSERT INTO users(Name,Birthdate,Introduction,Avatar,Email) VALUES('Orban Viktor', '1953.10.10','elnök','nincs','orban@gmail.com');
INSERT INTO users(Name,Birthdate,Introduction,Avatar,Email) VALUES('Lewis Hamilton', '1980.10.10','Best Pilota','nincs','lewis@gmail.com');
INSERT INTO users(Name,Birthdate,Introduction,Avatar,Email) VALUES('Code Cool', '2015.09.01','Suli','nincs','cc@gmail.com');
INSERT INTO users(Name,Birthdate,Introduction,Avatar,Email)	VALUES('Kertesz Geza', '1970.03.07','villany leo','bk','metilalkohol@gmail.com');
INSERT INTO meetups(Start,Location,Topic,Description) VALUES('2015.05.08','Miskolc, Codecool','Tanulas','Programozas oktatas');
INSERT INTO meetups(Start,Location,Topic,Description) VALUES('2015.09.10','Szeged, Kispark','Szorakozo','Gokart');
INSERT INTO meetups(Start,Location,Topic,Description) VALUES('2015.11.28','Pest, Keleti','Utazo','Vonat palyaudvar');
INSERT INTO meetups(Start,Location,Topic,Description) VALUES('2015.12.01','Eger, Pince','Ivo','Bor mertektelenul');
INSERT INTO meetups(Start,Location,Topic,Description) VALUES('2015.10.07','Tapola, Barlangfrdő','Uszkalo','Kikapcsolodas');
INSERT INTO meetupregistrations(StatusId,MeetupsId,UsersId) VALUES(1,1,1);
INSERT INTO meetupregistrations(StatusId,MeetupsId,UsersId) VALUES(1,1,2);
INSERT INTO meetupregistrations(StatusId,MeetupsId,UsersId)	VALUES(1,2,1);
INSERT INTO meetupregistrations(StatusId,MeetupsId,UsersId) VALUES(3,4,5);
INSERT INTO meetupregistrations(StatusId,MeetupsId,UsersId) VALUES(3,3,4);